export const currentlyInsuredOptions = [
  {
    label: "Yes",
    value: "Yes",
  },
  {
    label: "No",
    value: "No",
  },
];

export const coverageTypeOptions = [
  {
    label: "Minimum",
    value: "Minimum",
  },
  {
    label: "Basic",
    value: "Basic",
  },
  {
    label: "Standard",
    value: "Standard",
  },
  {
    label: "Superior",
    value: "Superior",
  },
];

export const bodilyInjuryOptions = [
  {
    label: "$10k/$20k",
    value: "10/20",
  },
  {
    label: "$15k/$30k",
    value: "15/30",
  },
  {
    label: "$25k/$50k",
    value: "25/50",
  },
  {
    label: "$50k/$100k",
    value: "50/100",
  },
  {
    label: "$100k/$300k",
    value: "100/300",
  },
  {
    label: "$250k/$500k",
    value: "250/500",
  },
  {
    label: "$500k/$500k",
    value: "500/500",
  },
];

export const propertyDamageOptions = [
  {
    label: "$10,000",
    value: "10000",
  },
  {
    label: "$15,000",
    value: "15000",
  },
  {
    label: "$20,000",
    value: "20000",
  },
  {
    label: "$25,000",
    value: "25000",
  },
  {
    label: "$30,000",
    value: "30000",
  },
  {
    label: "$35,000",
    value: "35000",
  },
  {
    label: "$40,000",
    value: "40000",
  },
  {
    label: "$50,000",
    value: "50000",
  },
  {
    label: "$75,000",
    value: "75000",
  },
  {
    label: "$100,000",
    value: "100000",
  },
];

export const vehicleCollisionOptions = [
  {
    label: "$0",
    value: "0",
  },
  {
    label: "$50",
    value: "50",
  },
  {
    label: "$100",
    value: "100",
  },
  {
    label: "$250",
    value: "250",
  },
  {
    label: "$500",
    value: "500",
  },

  {
    label: "$1,000",
    value: "1000",
  },
  {
    label: "$2,500",
    value: "2500",
  },
];

export const coverageTypes = [
  {
    label: "Minimum",
    value: "Minimum",
  },
  {
    label: "Basic",
    value: "Basic",
  },
  {
    label: "Standard",
    value: "Standard",
  },
  {
    label: "Full",
    value: "Full",
  },
  {
    label: "Superior",
    value: "Superior",
  },
];

export const insuranceCompanies = [
  { label: "My Insurance Is Not Listed", value: "Not Applicable" },
  { label: "21st Century", value: "21st Century Insurance" },
  { label: "AAA", value: "AAA Insurance" },
  { label: "AABCO", value: "AABCO" },
  { label: "AARP", value: "AARP" },
  { label: "Access Insurance", value: "Access Insurance" },
  { label: "Acordia", value: "Acordia" },
  { label: "Aegis Security", value: "Aegis Security" },
  { label: "AETNA", value: "AETNA" },
  { label: "Affirmative", value: "Affirmative" },
  { label: "AFLAC", value: "AFLAC" },
  { label: "AHCP", value: "AHCP" },
  { label: "AIG", value: "AIG" },
  { label: "AIU", value: "AIU" },
  { label: "All Nation", value: "All Nation" },
  { label: "All Risk", value: "All Risk" },
  { label: "Allianz", value: "Allianz" },
  { label: "Allied", value: "Allied" },
  { label: "Allstate", value: "Allstate" },
  { label: "American Alliance", value: "American Alliance" },
  {
    label: "American Automobile Insurance",
    value: "American Automobile Insurance",
  },
  { label: "American Banks", value: "American Banks" },
  { label: "American Casualty", value: "American Casualty" },
  { label: "American Deposit Insurance", value: "American Deposit Insurance" },
  {
    label: "American Direct Business Insurance",
    value: "American Direct Business Insurance",
  },
  { label: "American Economy", value: "American Economy" },
  { label: "American Empire Insurance", value: "American Empire Insurance" },
  { label: "American Family", value: "American Family" },
  { label: "American Financial", value: "American Financial" },
  {
    label: "American Health Underwriters",
    value: "American Health Underwriters",
  },
  { label: "American Home Assurance", value: "American Home Assurance" },
  { label: "American Insurance", value: "American Insurance" },
  { label: "American International", value: "American International" },
  {
    label: "American International Pacific",
    value: "American International Pacific",
  },
  {
    label: "American International South",
    value: "American International South",
  },
  { label: "American Manufacturers", value: "American Manufacturers" },
  {
    label: "American Mayflower Insurance",
    value: "American Mayflower Insurance",
  },
  {
    label: "American Medical Securities",
    value: "American Medical Securities",
  },
  {
    label: "American Motorists Insurance",
    value: "American Motorists Insurance",
  },
  { label: "American National", value: "American National" },
  {
    label: "American National Property and Casualty",
    value: "American National Property and Casualty",
  },
  { label: "American Premier", value: "American Premier" },
  {
    label: "American Protection Insurance",
    value: "American Protection Insurance",
  },
  { label: "American Reliable", value: "American Reliable" },
  { label: "American Republic", value: "American Republic" },
  { label: "American Savers Plan", value: "American Savers Plan" },
  { label: "American Service Insurance", value: "American Service Insurance" },
  {
    label: "American Skyline Insurance Company",
    value: "American Skyline Insurance Company",
  },
  { label: "American Spirit Insurance", value: "American Spirit Insurance" },
  { label: "American Standard", value: "American Standard" },
  { label: "American States", value: "American States" },
  { label: "America's Ins. Consultants", value: "America's Ins. Consultants" },
  { label: "AmeriPlan", value: "AmeriPlan" },
  { label: "Amerisure", value: "Amerisure" },
  { label: "Amica", value: "Amica" },
  { label: "Answer Financial", value: "Answer Financial" },
  { label: "Anthem", value: "Anthem" },
  { label: "API", value: "API" },
  { label: "Arbella", value: "Arbella" },
  { label: "Arizona General", value: "Arizona General" },
  { label: "Armed Forces Insurance", value: "Armed Forces Insurance" },
  { label: "Assigned Risk", value: "Assigned Risk" },
  { label: "Associated Indemnity", value: "Associated Indemnity" },
  {
    label: "Associated Insurance Managers",
    value: "Associated Insurance Managers",
  },
  { label: "Assurant", value: "Assurant" },
  { label: "Atlanta Casualty", value: "Atlanta Casualty" },
  { label: "Atlanta Specialty", value: "Atlanta Specialty" },
  { label: "Atlantic Indemnity", value: "Atlantic Indemnity" },
  { label: "Atlantis", value: "Atlantis" },
  { label: "Austin Mutual", value: "Austin Mutual" },
  {
    label: "Auto Club Insurance Company",
    value: "Auto Club Insurance Company",
  },
  { label: "Auto Owners", value: "Auto Owners" },
  { label: "Avomark", value: "Avomark" },
  { label: "AXA Advisors", value: "AXA Advisors" },
  { label: "Badger Mutual", value: "Badger Mutual" },
  { label: "Bankers & Shippers", value: "Bankers & Shippers" },
  { label: "Bankers Life and Casualty", value: "Bankers Life and Casualty" },
  { label: "Banner Life", value: "Banner Life" },
  { label: "Best Agency USA", value: "Best Agency USA" },
  { label: "Blue Cross", value: "Blue Cross" },
  { label: "Blue Cross / Blue Shield", value: "Blue Cross / Blue Shield" },
  { label: "Blue Shield of California", value: "Blue Shield of California" },
  { label: "Bonneville", value: "Bonneville" },
  { label: "Boston Old Colony", value: "Boston Old Colony" },
  { label: "Brooke Insurance", value: "Brooke Insurance" },
  { label: "Builders", value: "Builders" },
  { label: "Cal Farm Insurance", value: "Cal Farm Insurance" },
  { label: "California Casualty", value: "California Casualty" },
  {
    label: "California State Automobile Association",
    value: "California State Automobile Association",
  },
  { label: "Camden", value: "Camden" },
  { label: "Capital Choice", value: "Capital Choice" },
  { label: "Care Entrée", value: "Care Entrée" },
  { label: "Cascade National Ins", value: "Cascade National Ins" },
  { label: "Casualty Assurance", value: "Casualty Assurance" },
  { label: "Centennial", value: "Centennial" },
  { label: "Charter Oak", value: "Charter Oak" },
  { label: "Chase Insurance Group", value: "Chase Insurance Group" },
  { label: "Chicago Insurance", value: "Chicago Insurance" },
  { label: "Chubb", value: "Chubb" },
  { label: "Church Mutual", value: "Church Mutual" },
  { label: "Cigna", value: "Cigna" },
  { label: "Citizens", value: "Citizens" },
  { label: "Clarendon", value: "Clarendon" },
  {
    label: "Clarendon National Insurance",
    value: "Clarendon National Insurance",
  },
  { label: "Cloverleaf", value: "Cloverleaf" },
  { label: "CNA", value: "CNA" },
  { label: "Colonial", value: "Colonial" },
  { label: "Combined", value: "Combined" },
  { label: "Commercial Union", value: "Commercial Union" },
  { label: "Commonwealth", value: "Commonwealth" },
  { label: "Company Not Listed", value: "Company Not Listed" },
  { label: "Comparison Market", value: "Comparison Market" },
  { label: "Continental", value: "Continental" },
  { label: "Continental Casualty", value: "Continental Casualty" },
  {
    label: "Continental Divide Insurance",
    value: "Continental Divide Insurance",
  },
  { label: "Cotton States", value: "Cotton States" },
  { label: "Cottonwood", value: "Cottonwood" },
  {
    label: "Country Insurance and Financial Services",
    value: "Country Insurance and Financial Services",
  },
  { label: "Countrywide", value: "Countrywide" },
  { label: "Credit Union", value: "Credit Union" },
  { label: "Criterion", value: "Criterion" },
  { label: "CSE Insurance Group", value: "CSE Insurance Group" },
  { label: "CUNA Mutual", value: "CUNA Mutual" },
  { label: "Dairyland", value: "Dairyland" },
  { label: "Dakota Fire", value: "Dakota Fire" },
  { label: "Deerbrook", value: "Deerbrook" },
  { label: "Depositors Emcasc", value: "Depositors Emcasc" },
  { label: "Dixie", value: "Dixie" },
  { label: "Ebco General", value: "Ebco General" },
  { label: "Economy", value: "Economy" },
  { label: "Economy Fire & Casualty", value: "Economy Fire & Casualty" },
  { label: "Economy Preferred", value: "Economy Preferred" },
  { label: "eHealth", value: "eHealth" },
  { label: "Electric Insurance", value: "Electric Insurance" },
  { label: "EMC", value: "EMC" },
  { label: "Empire", value: "Empire" },
  { label: "Employers Fire", value: "Employers Fire" },
  { label: "Ensure", value: "Ensure" },
  { label: "Equitable Life", value: "Equitable Life" },
  { label: "Erie", value: "Erie" },
  { label: "Esurance", value: "Esurance" },
  { label: "Explorer", value: "Explorer" },
  { label: "Facility", value: "Facility" },
  { label: "Farm and Ranch", value: "Farm and Ranch" },
  { label: "Farm Bureau", value: "Farm Bureau" },
  { label: "Farm Bureau St. Pau", value: "Farm Bureau St. Pau" },
  { label: "Farmers", value: "Farmers" },
  { label: "Farmers Union", value: "Farmers Union" },
  { label: "Farmland", value: "Farmland" },
  { label: "Federal", value: "Federal" },
  { label: "Federated", value: "Federated" },
  { label: "Fidelity Insurance Company", value: "Fidelity Insurance Company" },
  { label: "FinanceBox.com", value: "FinanceBox.com" },
  { label: "Financial Indemnity", value: "Financial Indemnity" },
  {
    label: "Fire and Casualty Insurance Co of CT",
    value: "Fire and Casualty Insurance Co of CT",
  },
  { label: "Firemans Fund", value: "Firemans Fund" },
  { label: "First Acceptance Insurance", value: "First Acceptance Insurance" },
  { label: "First American", value: "First American" },
  { label: "First Financial", value: "First Financial" },
  { label: "First General", value: "First General" },
  { label: "First National", value: "First National" },
  { label: "Ford Motor Credit", value: "Ford Motor Credit" },
  { label: "Foremost", value: "Foremost" },
  { label: "Foresters", value: "Foresters" },
  { label: "Fortis", value: "Fortis" },
  { label: "Franklin", value: "Franklin" },
  { label: "Geico", value: "Geico" },
  { label: "General Accident", value: "General Accident" },
  { label: "General Insurance", value: "General Insurance" },
  { label: "Genworth Financial", value: "Genworth Financial" },
  { label: "Globe", value: "Globe" },
  { label: "GMAC", value: "GMAC" },
  { label: "Golden Rule", value: "Golden Rule / United Healthcare" },
  { label: "Golden Rule Insurance", value: "Golden Rule Insurance" },
  { label: "Government Employees", value: "Government Employees" },
  { label: "Grange", value: "Grange" },
  { label: "GRE Harleysville", value: "GRE Harleysville / Nationwide" },
  { label: "Great American", value: "Great American" },
  { label: "Great Way", value: "Great Way" },
  { label: "Great West", value: "Great West" },
  { label: "Grinnell Mutual", value: "Grinnell Mutual" },
  { label: "Guaranty National", value: "Guaranty National" },
  { label: "Guardian", value: "Guardian" },
  { label: "Guide One", value: "Guide One" },
  { label: "Halcyon", value: "Halcyon" },
  {
    label: "Hanover Lloyd's Insurance Company",
    value: "Hanover Lloyd's Insurance Company",
  },
  { label: "Happy Days", value: "Happy Days" },
  { label: "Hartford", value: "Hartford" },
  { label: "Hartford AARP", value: "Hartford AARP" },
  { label: "Hawkeye Security", value: "Hawkeye Security" },
  { label: "Health Benefits Direct", value: "Health Benefits Direct" },
  { label: "Health Choice One", value: "Health Choice One" },
  { label: "Health Net", value: "Health Net" },
  { label: "Health Plus of America", value: "Health Plus of America" },
  { label: "HealthShare American", value: "HealthShare American" },
  { label: "Heritage", value: "Heritage" },
  { label: "Horace Mann", value: "Horace Mann" },
  { label: "Humana", value: "Humana" },
  { label: "IAB", value: "IAB" },
  { label: "IDS", value: "IDS" },
  { label: "IFA Auto Insurance", value: "IFA Auto Insurance" },
  { label: "IGF", value: "IGF" },
  { label: "Independent", value: "Independent" },
  { label: "Infinity", value: "Infinity" },
  { label: "Insur. of Evanston", value: "Insur. of Evanston" },
  { label: "Insurance Insight", value: "Insurance Insight" },
  { label: "Insurance.com", value: "Insurance.com" },
  { label: "Integon", value: "Integon" },
  { label: "Interstate", value: "Interstate" },
  { label: "John Deere", value: "John Deere" },
  { label: "John Hancock", value: "John Hancock" },
  { label: "Kaiser Permanente", value: "Kaiser Permanente" },
  { label: "Kemper", value: "Kemper" },
  { label: "Kentucky Central", value: "Kentucky Central" },
  {
    label: "Landmark American Insurance",
    value: "Landmark American Insurance",
  },
  { label: "Leader Insurance", value: "Leader Insurance" },
  { label: "League General", value: "League General" },
  { label: "Liberty Insurance Corp", value: "Liberty Insurance Corp" },
  { label: "Liberty Mutual", value: "Liberty Mutual" },
  { label: "Liberty National", value: "Liberty National" },
  { label: "Liberty Northwest", value: "Liberty Northwest" },
  { label: "Lincoln Benefit Life", value: "Lincoln Benefit Life" },
  { label: "LTC Financial Partners", value: "LTC Financial Partners" },
  { label: "Lumbermens Mutual", value: "Lumbermens Mutual" },
  { label: "Marathon", value: "Marathon" },
  { label: "Markel American", value: "Markel American" },
  { label: "Maryland Casualty", value: "Maryland Casualty" },
  { label: "Mass Mutual", value: "Mass Mutual" },
  { label: "MEGA Life and Health", value: "MEGA Life and Health" },
  { label: "Mega/Midwest", value: "Mega/Midwest" },
  { label: "Mendota", value: "Mendota" },
  { label: "Merastar", value: "Merastar" },
  { label: "Mercury", value: "Mercury" },
  { label: "MetLife", value: "MetLife" },
  { label: "Mid Century Insurance", value: "Mid Century Insurance" },
  { label: "Mid-Continent Casualty", value: "Mid-Continent Casualty" },
  { label: "Middlesex Insurance", value: "Middlesex Insurance" },
  { label: "Midland National Life", value: "Midland National Life" },
  { label: "Midwest Mutual", value: "Midwest Mutual" },
  { label: "Millbank", value: "Millbank" },
  { label: "Millers Mutual", value: "Millers Mutual" },
  { label: "Milwaukee", value: "Milwaukee" },
  { label: "Milwaukee General", value: "Milwaukee General" },
  { label: "Milwaukee Guardian", value: "Milwaukee Guardian" },
  { label: "Milwaukee Mutual", value: "Milwaukee Mutual" },
  { label: "Minnehoma", value: "Minnehoma" },
  { label: "Missouri General", value: "Missouri General" },
  { label: "Modern Woodmen of America", value: "Modern Woodmen of America" },
  { label: "Mony Group", value: "Mony Group" },
  { label: "Mortgage Protection Bureau", value: "Mortgage Protection Bureau" },
  { label: "Motors", value: "Motors" },
  { label: "Mountain Laurel", value: "Mountain Laurel" },
  { label: "Mutual Insurance", value: "Mutual Insurance" },
  { label: "Mutual Of Enumclaw", value: "Mutual Of Enumclaw" },
  { label: "Mutual Of Omaha", value: "Mutual Of Omaha" },
  { label: "National Alliance", value: "National Alliance" },
  {
    label: "National Ben Franklin Insurance",
    value: "National Ben Franklin Insurance",
  },
  { label: "National Casualty", value: "National Casualty" },
  { label: "National Colonial", value: "National Colonial" },
  { label: "National Continental", value: "National Continental" },
  {
    label: "National Fire Insurance Company of Hartford",
    value: "National Fire Insurance Company of Hartford",
  },
  { label: "National Indemnity", value: "National Indemnity" },
  { label: "National Insurance", value: "National Insurance" },
  { label: "National Merit", value: "National Merit" },
  { label: "National Surety Corp", value: "National Surety Corp" },
  {
    label: "National Union Fire Insurance",
    value: "National Union Fire Insurance",
  },
  {
    label: "National Union Fire Insurance of LA",
    value: "National Union Fire Insurance of LA",
  },
  {
    label: "National Union Fire Insurance of PA",
    value: "National Union Fire Insurance of PA",
  },
  { label: "Nationwide", value: "Nationwide" },
  { label: "Nat'l Farmers Union", value: "Nat'l Farmers Union" },
  { label: "New England Financial", value: "New England Financial" },
  { label: "New York Life", value: "New York Life" },
  { label: "North American", value: "North American" },
  { label: "North Pacific", value: "North Pacific" },
  { label: "North Pointe", value: "North Pointe" },
  { label: "North Shore", value: "North Shore" },
  { label: "Northern Capital", value: "Northern Capital" },
  { label: "Northern States", value: "Northern States" },
  { label: "Northland", value: "Northland" },
  { label: "Northwest Pacific", value: "Northwest Pacific" },
  { label: "Northwestern", value: "Northwestern" },
  { label: "Northwestern Mutual", value: "Northwestern Mutual" },
  { label: "Northwestern Mutual Life", value: "Northwestern Mutual Life" },
  {
    label: "Northwestern Pacific Indemnity",
    value: "Northwestern Pacific Indemnity",
  },
  { label: "Ohio Casualty", value: "Ohio Casualty" },
  { label: "Ohio Security", value: "Ohio Security" },
  { label: "Olympia", value: "Olympia" },
  { label: "Omaha", value: "Omaha" },
  { label: "Omni Ins.", value: "Omni Ins." },
  { label: "Omni Insurance", value: "Omni Insurance" },
  { label: "Oregon Mutual", value: "Oregon Mutual" },
  { label: "Orion Ins.", value: "Orion Ins." },
  { label: "Orion Insurance", value: "Orion Insurance" },
  { label: "Other", value: "Other" },
  { label: "Pacific Indemnity", value: "Pacific Indemnity" },
  { label: "Pacific Insurance", value: "Pacific Insurance" },
  { label: "Pafco", value: "Pafco" },
  { label: "Paloverde", value: "Paloverde" },
  { label: "Patriot General", value: "Patriot General" },
  {
    label: "Peak Property and Casualty Insurance",
    value: "Peak Property and Casualty Insurance",
  },
  { label: "Pemco", value: "Pemco" },
  { label: "Penn America", value: "Penn America" },
  { label: "Penn Mutual", value: "Penn Mutual" },
  { label: "Pennsylvania Natl", value: "Pennsylvania Natl" },
  { label: "Phoenix", value: "Phoenix" },
  { label: "Physicians", value: "Physicians" },
  { label: "Pinnacle", value: "Pinnacle" },
  { label: "Pioneer Life", value: "Pioneer Life" },
  { label: "Preferred Abstainers", value: "Preferred Abstainers" },
  { label: "Preferred Mutual", value: "Preferred Mutual" },
  { label: "Premier", value: "Premier" },
  { label: "Prestige", value: "Prestige" },
  { label: "Primerica", value: "Primerica" },
  { label: "Principal Financial", value: "Principal Financial" },
  { label: "Progressive", value: "Progressive" },
  { label: "Protective Life", value: "Protective Life" },
  { label: "Provident", value: "Provident" },
  { label: "Prudential", value: "Prudential" },
  { label: "Quality", value: "Quality" },
  { label: "Ramsey", value: "Ramsey" },
  { label: "Ranger", value: "Ranger" },
  { label: "RBC Liberty", value: "RBC Liberty Insurance" },
  { label: "Regal", value: "Regal" },
  { label: "Reliance", value: "Reliance" },
  { label: "Reliant", value: "Reliant" },
  { label: "Republic Indemnity", value: "Republic Indemnity" },
  { label: "Response Insurance", value: "Response Insurance" },
  { label: "Rockford Mutual", value: "Rockford Mutual" },
  { label: "Rodney D. Young", value: "Rodney D. Young" },
  { label: "Safeco", value: "Safeco" },
  { label: "Safeway", value: "Safeway" },
  { label: "Sea West Insurance", value: "Sea West Insurance" },
  { label: "Secura", value: "Secura" },
  { label: "Security Insurance", value: "Security Insurance" },
  { label: "Security National", value: "Security National" },
  { label: "Sedgwick James", value: "Sedgwick James" },
  { label: "Sentinel Insurance", value: "Sentinel Insurance" },
  { label: "Sentry", value: "Sentry" },
  { label: "Shelter", value: "Shelter" },
  { label: "Skandia TIG Tita", value: "Skandia TIG Tita" },
  { label: "Spectrum", value: "Spectrum" },
  { label: "St. Paul", value: "St. Paul" },
  {
    label: "Standard Fire Insurance Company",
    value: "Standard Fire Insurance Company",
  },
  { label: "Standard Guaranty", value: "Standard Guaranty" },
  {
    label: "State and County Mutual Fire Insurance",
    value: "State and County Mutual Fire Insurance",
  },
  { label: "State Auto", value: "State Auto" },
  { label: "State Farm", value: "State Farm" },
  { label: "State Mutual", value: "State Mutual" },
  { label: "State National", value: "State National" },
  { label: "Sun Coast", value: "Sun Coast" },
  { label: "Superior", value: "Superior" },
  {
    label: "Superior Guaranty Insurance",
    value: "Superior Guaranty Insurance",
  },
  { label: "Sure Health Plans", value: "Sure Health Plans" },
  { label: "Sutter", value: "Sutter" },
  { label: "The Ahbe Group", value: "The Ahbe Group" },
  { label: "The Credo Group", value: "The Credo Group" },
  { label: "The General", value: "The General" },
  { label: "TICO Insurance", value: "TICO Insurance" },
  { label: "TIG Countrywide Insurance", value: "TIG Countrywide Insurance" },
  { label: "Titan", value: "Titan" },
  { label: "Total", value: "Total" },
  { label: "Tower", value: "Tower" },
  { label: "TransAmerica", value: "TransAmerica" },
  { label: "Travelers", value: "Travelers" },
  { label: "Trinity Universal", value: "Trinity Universal" },
  { label: "Tri-State Consumer", value: "Tri-State Consumer" },
  { label: "Trust Hall", value: "Trust Hall" },
  { label: "Twentieth Century", value: "Twentieth Century" },
  { label: "Twin City Fire Insurance", value: "Twin City Fire Insurance" },
  { label: "Unicare", value: "Unicare" },
  { label: "Uniguard", value: "Uniguard" },
  { label: "Union", value: "Union" },
  { label: "United American", value: "United American" },
  { label: "United Financial", value: "United Financial" },
  { label: "United Fire & Casual", value: "United Fire & Casual" },
  { label: "United Healthcare", value: "United Healthcare" },
  { label: "United Insurance", value: "United Insurance" },
  { label: "United Security", value: "United Security" },
  { label: "United Services Auto", value: "United Services Auto" },
  { label: "United States Fideli", value: "United States Fideli" },
  { label: "Unitrin", value: "Unitrin" },
  {
    label: "Universal Underwriters Insurance",
    value: "Universal Underwriters Insurance",
  },
  { label: "US Financial", value: "US Financial" },
  { label: "US Health Advisors", value: "US Health Advisors" },
  {
    label: "USA Benefits/Continental General",
    value: "USA Benefits/Continental General",
  },
  { label: "USAA", value: "USAA" },
  { label: "USF&G", value: "USF&G" },
  { label: "Utah Home and Fire", value: "Utah Home and Fire" },
  { label: "Utica", value: "Utica" },
  { label: "Vasa North Atlantic", value: "Vasa North Atlantic" },
  { label: "Vigilant", value: "Vigilant" },
  { label: "Viking", value: "Viking" },
  { label: "Wawaunesa", value: "Wawaunesa" },
  { label: "Wellington", value: "Wellington" },
  { label: "Wellpoint", value: "Wellpoint" },
  { label: "West American", value: "West American" },
  { label: "West Bend Mutual", value: "West Bend Mutual" },
  { label: "West Field", value: "West Field" },
  { label: "West Plains", value: "West Plains" },
  { label: "Western and Southern Life", value: "Western and Southern Life" },
  { label: "Western Mutual", value: "Western Mutual" },
  { label: "Western National", value: "Western National" },
  { label: "Western Southern Life", value: "Western Southern Life" },
  { label: "Westfield", value: "Westfield" },
  { label: "William Penn", value: "William Penn" },
  { label: "Windsor", value: "Windsor" },
  { label: "Windstar", value: "Windstar" },
  { label: "Wisconsin Mutual", value: "Wisconsin Mutual" },
  { label: "Woodlands Financial Group", value: "Woodlands Financial Group" },
  { label: "Workmans Auto", value: "Workmans Auto" },
  { label: "World Insurance", value: "World Insurance" },
  { label: "Worldwide", value: "Worldwide" },
  { label: "Yellow Key", value: "Yellow Key" },
  { label: "Yosemite", value: "Yosemite" },
  { label: "Zurich North America", value: "Zurich North America" },
];
