export const occupationOptions = {
  Advertising: "Advertising/Public Relations",
  Entertainer: "Arts/Entertainment/Publishing",
  Banker: "Banking/Mortgage",
  Clergy: "Clergy/Religious",
  Construction: "Construction/Facilities",
  CertifiedPublicAccountant: "CPA/Auditor",
  BankTeller: "Customer Service/Teller",
  Disabled: "Disabled",
  HealthCare: "Doctor/Dentist",
  Teacher: "Education/Training",
  Engineer: "Engineering/Architecture",
  Government: "Government",
  HealthCareWorker: "Health Care",
  Homemaker: "Homemaker",
  HospitalityTravel: "Hospitality/Travel",
  HumanResources: "Human Resources",
  Insurance: "Insurance",
  PoliceOfficer: "Law Enforcement/Security",
  Lawyer: "Legal",
  Administrative: "Management Consulting",
  MilitaryOfficer: "Military/Defense",
  OfficeWorker: "Office Worker/Clerical/Business Consulting",
  Other: "Other",
  RealEstate: "Real Estate",
  WaiterWaitress: "Restaurant/Food Service",
  Retail: "Retail",
  Retired: "Retired",
  Sales: "Sales",
  SelfEmployed: "Self Employed",
  SkilledWorker: "Skilled Worker",
  Student: "Student",
  Technology: "Technology",
  Telecommunications: "Telecommunications",
  DeliveryDriver: "Transportation/Logistics",
  Unemployed: "Unemployed",
};
